"""add access_log

Revision ID: 90589883a018
Revises: 28f8eb3b6d11
Create Date: 2026-09-03 10:50:36.920001
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "90589883a018"
down_revision: str | None = "28f8eb3b6d11"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "access_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("at", sa.String(), nullable=False),
        sa.Column("org_id", sa.String(), nullable=False),
        sa.Column("subject", sa.String(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("method", sa.String(), nullable=False),
        sa.Column("path", sa.String(), nullable=False),
        sa.Column("status", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_access_log_at"), "access_log", ["at"], unique=False)
    op.create_index(op.f("ix_access_log_org_id"), "access_log", ["org_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_access_log_org_id"), table_name="access_log")
    op.drop_index(op.f("ix_access_log_at"), table_name="access_log")
    op.drop_table("access_log")
    # ### end Alembic commands ###
